### ISSUE TITLE
findutils-4.2.33: infrequently 0.5% ABORT: make[2]: sh: Command not found

### ISSUE THREAD

**Issue by bittorf** [fosslinux/live-bootstrap#108] opened 2021-04-18 09:51 UTC
seen with f592186 (stikonas/unar) and qemu-386 with kernel 3.18.140 and 3G RAM.

see:
http://intercity-vpn.de/bootstrap/bootstrap.log-multilog-8-1618712725

```
[...]
00h55m20s | DEPDIR=.deps depmode=icc /bin/sh ../../depcomp \
00h55m20s | tcc -DHAVE_CONFIG_H -I. -I. -I../..  -I../../intl -D__UCLIBC__  -g -c alloca.c
00h55m20s | rm -f libgnulib.a
00h55m20s | ar cru libgnulib.a areadlink-with-size.o file-set.o fpurge.o freadahead.o freading.o hash-pjw.o hash-triple.o localcharset.o malloca.o openat-die.o progname.o xalloc-die.o xstrndup.o xstrtoumax.o argmatch.o basename.o canonicalize.o canonicalize-lgpl.o chdir-long.o close-stream.o closein.o closeout.o creat-safer.o dirname.o dup-safer.o error.o exitfail.o fd-safer.o filemode.o filenamecat.o fnmatch.o fopen-safer.o getcwd.o getopt.o getopt1.o hash.o human.o idcache.o modechange.o mountlist.o open-safer.o openat-proc.o pipe-safer.o quote.o quotearg.o regex.o rpmatch.o same.o save-cwd.o savedir.o strftime.o stripslash.o xgetcwd.o xmalloc.o xstrtol.o xstrtol-error.o xstrtoul.o yesno.o alloca.o
00h55m20s | ranlib libgnulib.a
00h55m20s | rm -f t-charset.alias charset.alias
00h55m20s | /bin/sh ./config.charset 'i486-pc-linux-gnuaout' > t-charset.alias
00h55m20s | mv t-charset.alias charset.alias
00h55m20s | rm -f t-ref-add.sed ref-add.sed
00h55m20s | sed -e '/^#/d' -e 's/@''PACKAGE''@/findutils/g' ref-add.sin > t-ref-add.sed
00h55m20s | mv t-ref-add.sed ref-add.sed
00h55m20s | rm -f t-ref-del.sed ref-del.sed
00h55m20s | sed -e '/^#/d' -e 's/@''PACKAGE''@/findutils/g' ref-del.sin > t-ref-del.sed
00h55m20s | mv t-ref-del.sed ref-del.sed
00h55m20s | make[4]: Leaving directory `/after/findutils-4.2.33/build/findutils-4.2.33/gnulib/lib'
00h55m20s | make[3]: Leaving directory `/after/findutils-4.2.33/build/findutils-4.2.33/gnulib/lib'
00h55m20s | make[3]: Entering directory `/after/findutils-4.2.33/build/findutils-4.2.33/gnulib'
00h55m20s | make[3]: Nothing to be done for `all-am'.
00h55m20s | make[3]: Leaving directory `/after/findutils-4.2.33/build/findutils-4.2.33/gnulib'
00h55m20s | make[2]: Leaving directory `/after/findutils-4.2.33/build/findutils-4.2.33/gnulib'
00h55m20s | Making all in lib
00h55m20s | make[2]: Entering directory `/after/findutils-4.2.33/build/findutils-4.2.33/lib'
00h55m20s | sh ./gnulib-version.sh .. .  ../import-gnulib.config
00h55m20s | make[2]: sh: Command not found
00h55m20s | make[2]: *** [gnulib-version.c] Error 127
00h55m20s | make[2]: Leaving directory `/after/findutils-4.2.33/build/findutils-4.2.33/lib'
00h55m20s | make[1]: *** [all-recursive] Error 1
00h55m20s | make[1]: Leaving directory `/after/findutils-4.2.33/build/findutils-4.2.33'
00h55m20s | make: *** [all] Error 2
00h55m20s | Subprocess error 512
00h55m20s | ABORTING HARD
```

**Comment by stikonas** [comment] 2021-04-18 10:40
Duplicate of #101

**Closed by stikonas** 2021-04-18 10:40 UTC
